# "cypress-io/cypress@3" installs the latest published
# version "s.x.y" of the orb. We recommend you then use
# the strict explicit version "cypress-io/cypress@3.x.y"
# to lock the version and prevent unexpected CI changes
# 추가적으로 CircleCI 대시보드에서 -> Organization -> Security 의 uncertified orbs도 설정 가능하게 해야 동작함..
# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1

executors:
  node-executor:
    docker:
      - image: cypress/browsers:node18.17.0-chrome104-ff102
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    working_directory: ~/repo

jobs:
  build_and_test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run production build
          command: npm run build && npm run start &
      - run:
          name: Wait for the server to be ready
          command: npx wait-on http://localhost:3000
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
# Cypress orb로 테스트 실행
# - cypress/run: # "run" job comes from "Cypress" orb
#     start-command: "npm run start"
