name: Codecov Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up a specific language environment (e.g., Node.js, Python, etc.)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install dependencies and run your tests
      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npx jest --coverage

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Add this token in your repo's secrets
          files: ./coverage/lcov.info # Adjust to your coverage report file
          flags: unittests # Optional: Add a flag to identify the report
          fail_ci_if_error: true # Fail the CI job if Codecov fails
