name: Test and get coverage

on:
  pull_request: # 새로운 PR이 생성될 때 실행
    branches:
      - main # 필요한 경우 특정 브랜치에만 동작하도록 설정

jobs:
  # 첫 번째 main: 빌드 실행
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20] # Node.js 버전 18, 20에서 실행

    steps:
      # 1. Node.js 환경 설정
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 2. 리포지토리 코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v4

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. 빌드 실행
      - name: Run build
        run: npm run build

      - name: Run tests
        run: npx jest --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
